jobs:
  include:
  - stage: Build docker images
    name: Geo rest
    language: minimal
    services:
    - docker
    install:
    - docker pull teamd2018/courier_emulator:latest
    script:
    - docker build -t $DOCKERHUB_OWNER/courier_emulator:$TRAVIS_COMMIT -f Dockerfile
      --cache-from teamd2018/courier_emulator:latest .
    - docker tag $DOCKERHUB_OWNER/courier_emulator:$TRAVIS_COMMIT $DOCKERHUB_OWNER/courier_emulator:latest
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_NAME" --password-stdin
    - docker push $DOCKERHUB_OWNER/courier_emulator
    if: branch = master
    branches:
      only:
      - master
  - stage: deploy
    language: bash
    deploy:
    - provider: script
      skip_cleanup: true
      script: bash deploy.sh $DEPLOY_TARGET
      on:
        branch: master
    - provider: script
      skip_cleanup: true
      script: bash deploy.sh $DEPLOY_TARGET
      on:
        branch: develop
    before_deploy:
    - openssl aes-256-cbc -K $encrypted_19a85d06465a_key -iv $encrypted_19a85d06465a_iv
      -in travis_key.enc -out ./travis_key -d
    if: branch = master
    branches:
      only:
      - master
